/*
 * Copyright (c) CompanyNameMagicTag 2012-2019. All rights reserved.
 * Description: The module name definition for all the MODULES
 * Author: audio
 */

#ifndef __DRV_AUDIO_DEV_H__
#define __DRV_AUDIO_DEV_H__

#ifdef __cplusplus
#if __cplusplus
extern "C" {
#endif
#endif

#define UMAP_NAME "soc_"

#define SOC_MOD_SYS "sys"
#define UMAP_DEVNAME_SYS UMAP_NAME SOC_MOD_SYS
#define UMAP_DEV_NUM_SYS 1
#define UMAP_MIN_MINOR_SYS 100
#define UMAP_MAX_MINOR_SYS (UMAP_MIN_MINOR_SYS + UMAP_DEV_NUM_SYS - 1)

#define SOC_MOD_AO "ao"
#define UMAP_DEVNAME_AO UMAP_NAME SOC_MOD_AO
#define UMAP_DEV_NUM_AO 1
#define UMAP_MIN_MINOR_AO (UMAP_MAX_MINOR_SYS + 1)
#define UMAP_MAX_MINOR_AO (UMAP_MIN_MINOR_AO + UMAP_DEV_NUM_AO - 1)

#define SOC_MOD_AI "ai"
#define UMAP_DEVNAME_AI UMAP_NAME SOC_MOD_AI
#define UMAP_DEV_NUM_AI 1
#define UMAP_MIN_MINOR_AI (UMAP_MAX_MINOR_AO + 1)
#define UMAP_MAX_MINOR_AI (UMAP_MIN_MINOR_AI + UMAP_DEV_NUM_AI - 1)

#define SOC_MOD_AENC "aenc"
#define UMAP_DEVNAME_AENC UMAP_NAME SOC_MOD_AENC
#define UMAP_DEV_NUM_AENC 1
#define UMAP_MIN_MINOR_AENC (UMAP_MAX_MINOR_AI + 1)
#define UMAP_MAX_MINOR_AENC (UMAP_MIN_MINOR_AENC + UMAP_DEV_NUM_AENC - 1)

#define SOC_MOD_ADEC "adec"
#define UMAP_DEVNAME_ADEC UMAP_NAME SOC_MOD_ADEC
#define UMAP_DEV_NUM_ADEC 1
#define UMAP_MIN_MINOR_ADEC (UMAP_MAX_MINOR_AENC + 1)
#define UMAP_MAX_MINOR_ADEC (UMAP_MIN_MINOR_ADEC + UMAP_DEV_NUM_ADEC - 1)

#define SOC_MOD_SEA "sea"
#define UMAP_DEVNAME_SEA UMAP_NAME SOC_MOD_SEA
#define UMAP_DEV_NUM_SEA 1
#define UMAP_MIN_MINOR_SEA (UMAP_MAX_MINOR_ADEC + 1)
#define UMAP_MAX_MINOR_SEA (UMAP_MIN_MINOR_SEA + UMAP_DEV_NUM_SEA - 1)

#define SOC_MOD_TRACK "track"
#define UMAP_DEVNAME_TRACK UMAP_NAME SOC_MOD_TRACK
#define UMAP_DEV_NUM_TRACK 1
#define UMAP_MIN_MINOR_TRACK (UMAP_MAX_MINOR_SEA + 1)
#define UMAP_MAX_MINOR_TRACK (UMAP_MIN_MINOR_TRACK + UMAP_DEV_NUM_TRACK - 1)

#define SOC_MOD_ADP "adp"
#define UMAP_DEVNAME_ADP UMAP_NAME SOC_MOD_ADP
#define UMAP_DEV_NUM_ADP 1
#define UMAP_MIN_MINOR_ADP (UMAP_MAX_MINOR_TRACK + 1)
#define UMAP_MAX_MINOR_ADP (UMAP_MIN_MINOR_ADP + UMAP_DEV_NUM_ADP - 1)

#define SOC_MOD_ANC "anc"
#define UMAP_DEVNAME_ANC UMAP_NAME SOC_MOD_ANC
#define UMAP_DEV_NUM_ANC 1
#define UMAP_MIN_MINOR_ANC (UMAP_MAX_MINOR_ADP + 1)
#define UMAP_MAX_MINOR_ANC (UMAP_MIN_MINOR_ANC + UMAP_DEV_NUM_ANC - 1)

#define SOC_MOD_AB "ab"
#define UMAP_DEVNAME_AB UMAP_NAME SOC_MOD_AB
#define UMAP_DEV_NUM_AB 1
#define UMAP_MIN_MINOR_AB (UMAP_MAX_MINOR_ANC + 1)
#define UMAP_MAX_MINOR_AB (UMAP_MIN_MINOR_AB + UMAP_DEV_NUM_AB - 1)

#define SOC_MOD_VAD "vad"
#define UMAP_DEVNAME_VAD UMAP_NAME SOC_MOD_VAD
#define UMAP_DEV_NUM_VAD 1
#define UMAP_MIN_MINOR_VAD (UMAP_MAX_MINOR_AB + 1)
#define UMAP_MAX_MINOR_VAD (UMAP_MIN_MINOR_VAD + UMAP_DEV_NUM_VAD - 1)

#define SOC_MOD_HAID "haid"
#define UMAP_DEVNAME_HAID UMAP_NAME SOC_MOD_HAID
#define UMAP_DEV_NUM_HAID 1
#define UMAP_MIN_MINOR_HAID (UMAP_MAX_MINOR_VAD + 1)
#define UMAP_MAX_MINOR_HAID (UMAP_MIN_MINOR_HAID + UMAP_DEV_NUM_HAID - 1)

#define SOC_MOD_VENDOR "vendor"
#define UMAP_DEVNAME_VENDOR UMAP_NAME SOC_MOD_VENDOR
#define UMAP_DEV_NUM_VENDOR 1
#define UMAP_MIN_MINOR_VENDOR (UMAP_MAX_MINOR_HAID + 1)
#define UMAP_MAX_MINOR_VENDOR (UMAP_MIN_MINOR_VENDOR + UMAP_DEV_NUM_VENDOR - 1)

#define SOC_MOD_DPM "dpm"
#define UMAP_DEVNAME_DPM UMAP_NAME SOC_MOD_DPM
#define UMAP_DEV_NUM_DPM 1
#define UMAP_MIN_MINOR_DPM (UMAP_MAX_MINOR_VENDOR + 1)
#define UMAP_MAX_MINOR_DPM (UMAP_MIN_MINOR_DPM + UMAP_DEV_NUM_DPM - 1)

#define UMAP_DEV_NUM_TOTAL UMAP_MAX_MINOR_DPM

#define IOC_TYPE_DEMUX 'I'
#define IOC_TYPE_MEM 'J'
#define IOC_TYPE_RELEASE 'K'
#define IOC_TYPE_EVENT 'L'
#define IOC_TYPE_SYS 'M'
#define IOC_TYPE_STAT 'N'
#define IOC_TYPE_MCC 'O'
#define IOC_TYPE_TDE 'P'

#define IOC_TYPE_CIPHER 'Q'
#define IOC_TYPE_AVPLAY 'R'

#define IOC_TYPE_VI 'S'
#define IOC_TYPE_VENC 'T'
#define IOC_TYPE_CA 'U'
#define IOC_TYPE_OTP 'V'

#define IOC_TYPE_VP 'W'
#define IOC_TYPE_VICAP 'X'
#define IOC_TYPE_SIF 'Y'

#ifdef __cplusplus
#if __cplusplus
}
#endif
#endif /* __cplusplus */

#endif
