/*
 * Copyright (c) CompanyNameMagicTag 2022-2022. All rights reserved.
 * Description: define the sap drv ioctl cmd
 * Author: audio
 * Create: 2022-12-09
 */

#ifndef __DRV_SAP_IOCTL_CMD_H__
#define __DRV_SAP_IOCTL_CMD_H__

enum {
    CMD_SYS_INIT = 0,
    CMD_SYS_DEINIT,
    CMD_SYS_SET_STATE,
    CMD_SYS_SET_DEBUG_CFG,
    CMD_SYS_GET_DEBUG_CFG,
    CMD_SYS_SET_PRODUCT_FORM,
    CMD_SYS_SET_TWS_MONO_MODE,
    CMD_SYS_SET_TWS_MODE,
    CMD_SYS_SET_TWS_ROLE,
    CMD_SYS_SET_DSP_LOG_LEVEL,

    CMD_SYS_ID_MAX,
};

enum {
    CMD_ADP_INIT = 0,
    CMD_ADP_DEINIT,
    CMD_ADP_GET_DEF_ATTR,
    CMD_ADP_OPEN,
    CMD_ADP_CLOSE,
    CMD_ADP_ALLOC_SHRB,
    CMD_ADP_FREE_SHRB,
    CMD_ADP_MAP,
    CMD_ADP_UNMAP,
    CMD_ADP_GET_ATTR,
    CMD_ADP_SET_ATTR,
    CMD_ADP_ATTACH_OUTPUT,
    CMD_ADP_DETACH_OUTPUT,
    CMD_ADP_REG_EVENT_PROC,
    CMD_ADP_ID_MAX,
};

enum {
    CMD_AI_INIT = 0,
    CMD_AI_DEINIT,
    CMD_AI_GET_DEF_ATTR,
    CMD_AI_OPEN,
    CMD_AI_CLOSE,
    CMD_AI_REG_EVENT_PROC,
    CMD_AI_START,
    CMD_AI_STOP,
    CMD_AI_GET_ATTR,
    CMD_AI_SET_ATTR,
    CMD_AI_SET_BYPASS,
    CMD_AI_RESET_VAD,
    CMD_AI_GET_GAIN,
    CMD_AI_SET_GAIN,
    CMD_AI_GET_MUTE,
    CMD_AI_SET_MUTE,
    CMD_AI_SET_MIC_CALI_VOLUME,
    CMD_AI_ATTACH_OUTPUT,
    CMD_AI_DETACH_OUTPUT,
    CMD_AI_ID_MAX,
};

enum {
    CMD_VAD_INIT = 0,
    CMD_VAD_DEINIT,
    CMD_VAD_GET_DEF_ATTR,
    CMD_VAD_OPEN,
    CMD_VAD_CLOSE,
    CMD_VAD_REG_EVENT_PROC,
    CMD_VAD_RESET,
    CMD_VAD_ID_MAX,
};

enum {
    CMD_SEA_INIT = 0,
    CMD_SEA_DEINIT,
    CMD_SEA_LOAD,
    CMD_SEA_UNLOAD,
    CMD_SEA_GET_ENG_CAPS,
    CMD_SEA_GET_DEF_ATTR,
    CMD_SEA_CREATE,
    CMD_SEA_DESTROY,
    CMD_SEA_REG_EVENT_PROC,
    CMD_SEA_START,
    CMD_SEA_STOP,
    CMD_SEA_GET_ENG_ATTR,
    CMD_SEA_SET_ENG_ATTR,
    CMD_SEA_GET_PCM_ATTR,
    CMD_SEA_SET_PCM_ATTR,
    CMD_SEA_GET_PARAM,
    CMD_SEA_SET_PARAM,
    CMD_SEA_SET_BYPASS,
    CMD_SEA_GET_ITEM_COUNT,
    CMD_SEA_GET_ITEM_SETS,
    CMD_SEA_ADD_ITEM,
    CMD_SEA_REMOVE_ITEM,
    CMD_SEA_ENABLE_VID_ENROLL,
    CMD_SEA_ATTACH_OUTPUT,
    CMD_SEA_DETACH_OUTPUT,
    CMD_SEA_ID_MAX,
};

enum {
    CMD_ADEC_INIT = 0,
    CMD_ADEC_DEINIT,
    CMD_ADEC_LOAD,
    CMD_ADEC_UNLOAD,
    CMD_ADEC_OPEN,
    CMD_ADEC_CLOSE,
    CMD_ADEC_REG_EVENT_PROC,
    CMD_ADEC_START,
    CMD_ADEC_STOP,
    CMD_ADEC_GET_ATTR,
    CMD_ADEC_SET_ATTR,
    CMD_ADEC_SET_BYPASS,
    CMD_ADEC_ATTACH_OUTPUT,
    CMD_ADEC_DETACH_OUTPUT,
    CMD_ADEC_ID_MAX,
};

enum {
    CMD_AENC_INIT = 0,
    CMD_AENC_DEINIT,
    CMD_AENC_LOAD,
    CMD_AENC_UNLOAD,
    CMD_AENC_OPEN,
    CMD_AENC_CLOSE,
    CMD_AENC_REG_EVENT_PROC,
    CMD_AENC_START,
    CMD_AENC_STOP,
    CMD_AENC_GET_ATTR,
    CMD_AENC_SET_ATTR,
    CMD_AENC_SET_BYPASS,
    CMD_AENC_ATTACH_OUTPUT,
    CMD_AENC_DETACH_OUTPUT,
    CMD_AENC_SET_PARAM,
    CMD_AENC_ID_MAX,
};

enum {
    CMD_TRACK_INIT = 0,
    CMD_TRACK_DEINIT,
    CMD_TRACK_GET_DEF_ATTR,
    CMD_TRACK_OPEN,
    CMD_TRACK_CLOSE,
    CMD_TRACK_REG_EVENT_PROC,
    CMD_TRACK_GET_STATE,
    CMD_TRACK_SET_STATE,
    CMD_TRACK_GET_ATTR,
    CMD_TRACK_SET_ATTR,
    CMD_TRACK_GET_MUTE,
    CMD_TRACK_SET_MUTE,
    CMD_TRACK_GET_VOLUME,
    CMD_TRACK_SET_VOLUME,
    CMD_TRACK_SET_BYPASS,
    CMD_TRACK_ATTACH_OUTPUT,
    CMD_TRACK_DETACH_OUTPUT,
    CMD_TRACK_GET_PTS,
    CMD_TRACK_ID_MAX,
};

enum {
    CMD_AO_INIT = 0,
    CMD_AO_DEINIT,
    CMD_AO_GET_DEF_ATTR,
    CMD_AO_OPEN,
    CMD_AO_CLOSE,
    CMD_AO_REG_EVENT_PROC,
    CMD_AO_GET_PORT_ENABLE,
    CMD_AO_SET_PORT_ENABLE,
    CMD_AO_GET_MUTE,
    CMD_AO_SET_MUTE,
    CMD_AO_GET_VOLUME,
    CMD_AO_SET_VOLUME,
    CMD_AO_GET_TRACK_MODE,
    CMD_AO_SET_TRACK_MODE,
    CMD_AO_GET_ALL_TRACK_MUTE,
    CMD_AO_SET_ALL_TRACK_MUTE,
    CMD_AO_SET_BYPASS,
    CMD_AO_ATTACH_OUTPUT,
    CMD_AO_DETACH_OUTPUT,
    CMD_AO_GET_AEF_PARAM,
    CMD_AO_SET_AEF_PARAM,
    CMD_AO_GET_PORT_AEF_ENABLE,
    CMD_AO_SET_PORT_AEF_ENABLE,
    CMD_AO_SET_AEF_PROFILE,
    CMD_AO_SET_SPK_CALI,
    CMD_AO_ID_MAX,
};

enum {
    CMD_ANC_SET_CONFIG = 0,
    CMD_ANC_GET_CONFIG,
    CMD_ANC_ID_MAX,
};

enum {
    CMD_HAID_GET_DEFAULT_ATTR = 0,
    CMD_HAID_CREATE,
    CMD_HAID_DESTROY,
    CMD_HAID_SET_ENABLE,
    CMD_HAID_GET_ENABLE,
    CMD_HAID_REGISTER_EVENT_PROC,
    CMD_HAID_SET_VOLUME,
    CMD_HAID_GET_VOLUME,
    CMD_HAID_SET_CONFIG,
    CMD_HAID_GET_CONFIG,
    CMD_HAID_SET_HARDWARE_CONFIG,
    CMD_HAID_GET_HARDWARE_CONFIG,
    CMD_HAID_SET_ALL_CONFIG,
    CMD_HAID_GET_ALL_CONFIG,
    CMD_HAID_SINUS_TONE_START,
    CMD_HAID_SINUS_TONE_STOP,
    CMD_HAID_SET_SCENE,
    CMD_HAID_GET_SCENE,
    CMD_HAID_SET_SPK_CALI,
    CMD_HAID_SET_MIC_CALI_VOLUME,

    CMD_HAID_ID_MAX,
};

enum {
    CMD_DPM_INIT = 0,
    CMD_DPM_DEINIT,
    CMD_DPM_LOAD,
    CMD_DPM_UNLOAD,
    CMD_DPM_OPEN,
    CMD_DPM_CLOSE,
    CMD_DPM_REG_EVENT_PROC,
    CMD_DPM_START,
    CMD_DPM_STOP,
    CMD_DPM_GET_ATTR,
    CMD_DPM_SET_ATTR,
    CMD_DPM_SET_BYPASS,
    CMD_DPM_ATTACH_OUTPUT,
    CMD_DPM_DETACH_OUTPUT,
    CMD_DPM_ID_MAX,
};

#endif /* __DRV_SAP_IOCTL_H__ */
