/*
 * Copyright (c) CompanyNameMagicTag 2020-2020. All rights reserved.
 * Description: dsp interrupt type define
 * Author: audio
 */

#ifndef __INTERRUPT_TYPE_H__
#define __INTERRUPT_TYPE_H__

#ifdef __cplusplus
#if __cplusplus
extern "C" {
#endif
#endif

typedef enum {
    ADSP_INTERRUPT_NMI = 0,
    ADSP_INTERRUPT_SW,
    ADSP_INTERRUPT_BT2HIFI0_INT0,
    ADSP_INTERRUPT_BT2HIFI0_INT1,
    ADSP_INTERRUPT_MCU2HIFI0_INT0,
    ADSP_INTERRUPT_TIMER0,
    ADSP_INTERRUPT_TIMER1,
    ADSP_INTERRUPT_MCU2HIFI0_INT1,
    ADSP_INTERRUPT_DSP0_TIMER0_0,
    ADSP_INTERRUPT_DSP0_TIMER0_1,
    ADSP_INTERRUPT_RESERVED_0, /* anc todsp interrupt id is 10 */
    ADSP_INTERRUPT_RESERVED_1,
    ADSP_INTERRUPT_RESERVED_2,
    ADSP_INTERRUPT_DSP0_WDOG0_INT,
    ADSP_INTERRUPT_DSP0_I2C_INT,
    ADSP_INTERRUPT_DSP0_UART0_INT,
    ADSP_INTERRUPT_RESERVED_3,
    ADSP_INTERRUPT_DSP0_GPIO_INT,
    ADSP_INTERRUPT_DSP0_DMAC0_S_INT,
    ADSP_INTERRUPT_PROFILING,
    ADSP_INTERRUPT_DSP0_DMAC0_NS_INT,
    ADSP_INTERRUPT_RESERVED_4,
    ADSP_INTERRUPT_DSP0_VSET_INT,
    ADSP_INTERRUPT_DSP0_BT_TOG_POS,
    ADSP_INTERRUPT_DSP0_BT_TOG_NEG,
    ADSP_INTERRUPT_DSP0_RTC_INT,
    ADSP_INTERRUPT_RESERVED_5,
    ADSP_INTERRUPT_DSP0_ACCESS_MONITOR,
    ADSP_INTERRUPT_DSP0_MAD_ASR_INT,
    ADSP_INTERRUPT_WRITE_BUS_ERR,
    ADSP_INTERRUPT_RESERVED_6,
    ADSP_INTERRUPT_RESERVED_7,

    ADSP_INT_MAX,
} adsp_int_type;

#ifdef __cplusplus
#if __cplusplus
}
#endif /* __cplusplus */
#endif /* __cplusplus */

#endif /* __INTERRUPT_TYPE_H__ */
