/*
 * Copyright (c) CompanyNameMagicTag 2020-2020. All rights reserved.
 * Description: dsp reg
 * Author: audio
 */

#ifndef __MEM_ADDR_H__
#define __MEM_ADDR_H__

#include "chip_type.h"
#include "common_dsp.h"

#ifdef BRANDY_PROT /* bt core core id */
#define SHRB_CORE_K AUDIO_CORE_MCU0
#define SHRB_CORE_U AUDIO_CORE_MCU0

#else /* acore core id */
#define SHRB_CORE_K AUDIO_CORE_CPU_K
#define SHRB_CORE_U AUDIO_CORE_CPU_K
#endif /* BRANDY_PROT */

/* common memory tlb in reset-vector.S */
#define COM_MEM_AUDIO_VIRT_ADDR 0xA7000000
#define COM_MEM_AUDIO_PHYS_ADDR 0x87000000
#define COM_MEM_ACORE_PHYS_ADDR 0x87000000
#define COM_MEM_MAP_SIZE 0x100000

#define SHM_ADDR COM_MEM_AUDIO_VIRT_ADDR
#if (SAP_OS_TYPE == os_type_xtensa)
#define SHM_MAP_ADDR COM_MEM_AUDIO_VIRT_ADDR
#else
#define SHM_MAP_ADDR COM_MEM_ACORE_PHYS_ADDR
#endif

#define SOC_SHM_AUDIO_PHYS_ADDR 0x87000000
#define SOC_SHM_ACORE_PHYS_ADDR 0x87000000

#define SOC_PSRAM_AUDIO_PHYS_ADDR 0x8C201000
#define SOC_PSRAM_ACORE_PHYS_ADDR 0x6C201000

#define SOC_OCRAM_AUDIO_PHYS_ADDR 0xE815C000
#define SOC_OCRAM_ACORE_PHYS_ADDR 0x5815C000

#define SOC_L2RAM_AUDIO_VIRT_ADDR  0xC8500000
#define SOC_L2RAM_AUDIO_REMAP_ADDR 0xE8500000
#define SOC_L2RAM_AUDIO_PHYS_ADDR  0x80240000
#define SOC_L2RAM_ACORE_PHYS_ADDR  0x60240000
#define SOC_L2RAM_SIZE             0x00020000

/* tlb in reset-vector.S */
#define SOC_MEM_AUDIO_VIRT_ADDR 0xC8000000
#define SOC_MEM_AUDIO_PHYS_ADDR 0xE8000000
#define SOC_MEM_ACORE_PHYS_ADDR 0x58000000
#define SOC_MEM_MAP_SIZE        0x18000000

#define SRAM_AUDIO_VIRT_ADDR (SOC_OCRAM_AUDIO_PHYS_ADDR - SOC_MEM_AUDIO_PHYS_ADDR + SOC_MEM_AUDIO_VIRT_ADDR)
#define SRAM_AUDIO_PHYS_ADDR SOC_OCRAM_AUDIO_PHYS_ADDR
#define SRAM_ACORE_PHYS_ADDR SOC_OCRAM_ACORE_PHYS_ADDR

/* DSP DTCM map */
#define SOC_MEM_AUDIO_DTCM_REMAP_PHYS_ADDR  0xE8058000
#define SOC_MEM_AUDIO_DTCM_LOGIC_PHYS_ADDR  0xE8014000
#define SOC_MEM_AUDIO_DTCM_SIZE             0x28000

#define SRAM_ADDR        SRAM_AUDIO_VIRT_ADDR
#ifdef SAP_SEA_SEE_PHS_SUPPORT
#define SRAM_SIZE (SIZE_1M + SIZE_256K)
#else
#define SRAM_SIZE SIZE_1M
#endif

#if (SAP_OS_TYPE == os_type_xtensa)
#define SRAM_MAP_ADDR  SRAM_AUDIO_VIRT_ADDR
#else
#define SRAM_MAP_ADDR  SRAM_ACORE_PHYS_ADDR
#endif

#define DRAM_ADDR      0xe8058000
#define DRAM_SIZE      (SIZE_32K + SIZE_128K)
#if (SAP_OS_TYPE == os_type_xtensa)
#define DRAM_MAP_ADDR  DRAM_ADDR
#else
#define DRAM_MAP_ADDR  0x58014000
#endif
#define ACORE_DSP0_DRAM_ADDR DRAM_MAP_ADDR
#define ACORE_DSP1_DRAM_ADDR 0x00000000

#define IRAM_ADDR      0xe8080000
#define IRAM_SIZE      (SIZE_32K + SIZE_16K)
#if (SAP_OS_TYPE == os_type_xtensa)
#define IRAM_MAP_ADDR  IRAM_ADDR
#else
#define IRAM_MAP_ADDR  0x5803C000
#endif
#define ACORE_DSP0_IRAM_ADDR IRAM_MAP_ADDR
#define ACORE_DSP1_IRAM_ADDR 0x00000000

#define SHM0_ADDR      SOC_SHM_AUDIO_PHYS_ADDR
#define SHM0_SIZE      (SIZE_64K - SIZE_04K)

/* share memory on SOC Share MEM */
#define SOC_SYS_SHM_BASE_ADDR    SHM0_ADDR
#define SOC_SYS_SHM_BASE_SIZE    SAP_SHM_BASE_SIZE
#define SOC_SYS_SHM_MAX_SIZE     SHM0_SIZE

#define SOC_SYS_SHM_REG_BASE     (SOC_SYS_SHM_BASE_ADDR)
#define SOC_IPC_SYS_STATE_ADDR   (SOC_SYS_SHM_REG_BASE + SAP_SHM_SYS_CMD_OFFSET)
#define SOC_IPC_PROBE_STATUS_ADDR  (SOC_SYS_SHM_REG_BASE + SAP_SHM_PROBE_STATUS_OFFSET)
#define SOC_IPC_ADP_SHARE_BASE_ADDR (SOC_SYS_SHM_REG_BASE + SAP_SHM_ADP_IDS_OFFSET)
#define SOC_IPC_SHM_BASE_ADDR    (SOC_SYS_SHM_REG_BASE + SAP_SHM_SHRB_CFG_OFFSET)
#define SOC_SND_TRACK_PTS_ADDR   (SOC_SYS_SHM_REG_BASE + SAP_SHM_TRACK_PTS_OFFSET)
#define SOC_TWS_CONFIG_ADDR      (SOC_SYS_SHM_REG_BASE + SAP_SHM_TWS_CONFIG_OFFSET)

/* DSP firmware flash addr */
#define FLASH_BASEADDR           0x70000000
#define FLASH_DSP_MAIN_OFFSET    0x120000
#define FLASH_DSP_OVERLAY_OFFSET 0x200000

#define FLASH_DSP_MAIN_ADDR      (FLASH_BASEADDR + FLASH_DSP_MAIN_OFFSET)
#define FLASH_DSP_MAIN_SIZE      (SIZE_1M - SIZE_128K) /* 0x000E0000 */

#define FLASH_DSP_OVERLAY_ADDR   (FLASH_BASEADDR + FLASH_DSP_OVERLAY_OFFSET)
#define FLASH_DSP_OVERLAY_SIZE   (SIZE_1M + SIZE_256K) /* 0x00140000 */

#define FLASH_DSP_LIB_OFFSET   0x200000
#define FLASH_DSP_LIB_ADDR     FLASH_DSP_OVERLAY_ADDR
#define FLASH_DSP_LIB_SIZE     FLASH_DSP_OVERLAY_SIZE

#endif /* __MEM_ADDR_H__ */
