/*
 * Copyright (c) @CompanyNameMagicTag 2018-2020. All rights reserved.
 * Description:  common logging producer interface - need to change name of log.h in all the protocol core files
 * Author: @CompanyNameTag
 * Create:
 */

#ifndef LOG_DEF_PF_H
#define LOG_DEF_PF_H

typedef enum {
    // Platform 0-1024
    SECURITY_MAIN_C = 0,
    APP_OS_INIT_C,
    THREAD_INIT_C,
    SEC_OS_INIT_C,
    LOG_OAM_MSG_C,
    LOG_OML_EXCEPTION_C,
    BACKTRACE_C_NOT_USED_C,
    PANIC_C,
    RUNTIME_MONITOR_C,
    LOS_TASK_C,
    LOG_C,
    LOW_POWER_CONTROL_C,
    CPU_UTILS_C,
    HAL_PVSENSOR_C,
    PMU_CMU_C,
    GPIO_C,
    IR_C,
    CPU_TRACE_C,
    XIP_C,
    HAL_LPC_CORE_C,
    MPU_C,
    HAL_CPU_HIFI_C,
    IPC_C,
    FIRMWARE_VERSION_C,
    HAL_ADC_C,
    PATCH_C,
    PMU_INTERRUPT_C,
    HAL_CPU_CORE_C,
    COMMU_INTERFACE_C,
    EPMU_COUL_DRV_C,
    EPMU_COUL_CORE_C,
    EPMU_C,
    GNSS_OS_INIT_C,
    HAL_IPC_IRQ_C,
    PAL_LPM_C,
    PRESERVE_C,
    LITEOS_INFO_C,
    CLOCKS_CORE_C,
    SYSTEM_INFO_C,
    CPU_LOAD_C,
    PMU_C,
    LOS_STATUS_C,
    GNSS_PMU_C,
    PATCH_RISCV_C,
    PM_CONTROL_C,
    BLE_HID_SERVER_C,
    MAIN_C,
    LOG_OAM_REG_QUERY_C,
    PM_CLOCKS_C,
    DIAG_DFX_C,
    LOG_BUFFER_READER_C,
    LOG_UART_C,
    SOC_NV_STORAGE_HANDLE_C,
    SOC_NV_STORAGE_C,
    NV_CRYPTO_C,
    NV_KEY_C,
    NV_NOTIFY_C,
    NV_NVREGION_C,
    NV_PAGE_C,
    NV_RESET_C,
    NV_STORE_C,
    NV_UPDATE_C,
    NV_UPG_C,
    NV_ASYNC_STORE_C,
    DFX_SYSTEM_INIT_C,
    DFX_CHANNEL_C,
    SAMPLE_DATA_ADAPT_C,
    ZDIAG_ADAPT_SDT_C,
    MON_LOG_OUTPUT_C,
    DIAG_CMD_DST_C,
    DIAG_DEBUG_C,
    DIAG_FILTER_C,
    DIAG_MEM_C,
    DIAG_MSG_C,
    DIAG_PKT_ROUTER_C,
    DIAG_SERVICE_C,
    DIAG_STAT_C,
    DIAG_TX_C,
    DIAG_IND_SRC_C,
    DIAG_UPDATE_C,
    ZDIAG_AUDIO_HOOK_C,
    LAST_DUMP_C,
    DIAG_AUDIO_SAMPLE_DATA_C,
    DIAG_BT_SAMPLE_DATA_C,
    TRANSMIT_CMD_DELETE_FILE_C,
    TRANSMIT_CMD_DUMP_BY_NAME_C,
    TRANSMIT_CMD_LS_C,
    TRANSMIT_DEBUG_C,
    TRANSMIT_DST_C,
    DFX_FILE_OPERATION_C,
    TRANSMIT_ITEM_C,
    TRANSMIT_SRC_C,
    TRANSMIT_WRITE_READ_C,
    LOG_FILE_C,
    LOG_FILE_FILE_C,
    LOG_FILE_FLASH_C,
    PF_FILE_ID_MAX = 1024,
} log_file_list_enum_pf_app_t;

#endif
