/*
 * Copyright (c) @CompanyNameMagicTag 2022-2023. All rights reserved.
 * Description: Default memory configurations
 * Author: @CompanyNameTag
 */

#ifndef FLASH_8M_H
#define FLASH_8M_H

/*
 * ********************* FLASH ALLOCATION *********************
 * Flash is shared between the cores, and also handles a limited number of
 * non-volatile storage areas.
 *
 * Flash is split into 2 main areas
 * IMAGE Area
 *  Managed by the BT core
 *  This contains, in order from the bottom of Flash:
 *      SSB - SSB image starting at the bottom of flash. Variable size depending on the SSB on the chip that
 *            the package is loaded on. The values in this file only apply to the SSB built with this file.
 *      RECOVERY_Image   - starts in the page after the SSB.
 *      BT_Image         - starts in the page after the RECOVERY_Image
 *      DSP_Image        - starts in the page after the BT_Image
 *      APP_Image        - starts in the page after the DSP_Image
 *      System On-demand region - dynamically allocated flash for FOTA etc
 * NV Area
 *  Ends at the last page of flash, is configurable in size above a minimum allocation.
 *  NV Area, of 12 pages, is allocated, from the lowest address:
 *      8 pages of general use (pages are not fixed and self-identifying), consisting of
 *          1 Page for Asset Store defragmentation
 *          3 pages for Asset Store
 *          2 Pages for App and DSP Core KV defragmentation
 *          1 page for DSP Core KV
 *          1 page for App Core KV
 *      2 pages for BT core use (last 2 pages in Flash)
 *          1 page for BT Core KV
 *          1 page for BT Core KV defragmentation
 */

#define FLASH_START     0x70000000
#define FLASH_LENGTH    0x800000
#define FLASH_MAX_END   (FLASH_START + FLASH_LENGTH)

#define FLASH_PAGE_SIZE 4096
/* APP ITCM config */
#define MCU_ITCM_END    (APP_ITCM_ORIGIN + APP_ITCM_LENGTH)

#define SSB_BOOT_RAM_ORIGIN APP_ITCM_ORIGIN
#define SSB_BOOT_RAM_LENGTH APP_ITCM_LENGTH

/* ----------------------------------------------------------------------------------------------------------------- */
/* IMAGE Area Defines */
/* MCU SSB Region */
#define SSB_FLASH_REGION_PAGES  (SSB_IMAGE_PAGES + 5)
#define KV_PAGES 0
#define SSB_FLASH_REGION_START  (FLASH_START)
#define SSB_FLASH_REGION_LENGTH (SSB_FLASH_REGION_PAGES * FLASH_PAGE_SIZE)

#define SSB_VECTORS_LOAD_ORIGIN (SSB_FLASH_REGION_START)
#define SSB_VERSION_LOAD_ORIGIN (SSB_VECTORS_LOAD_ORIGIN + APP_VECTORS_LENGTH)
#define SSB_CHANGEID_LOAD_ORIGIN (SSB_VERSION_LOAD_ORIGIN + VERSION_LENGTH)

#define SSB_PROGRAM_ORIGIN (SSB_CHANGEID_LOAD_ORIGIN + CHANGE_ID_LENGTH)
#define SSB_PROGRAM_LENGTH ((SSB_FLASH_REGION_LENGTH) - (APP_VECTORS_LENGTH + VERSION_LENGTH + CHANGE_ID_LENGTH))

/* MCU SSB BACK-UP Region */
#define SSB_BACKUP_FLASH_REGION_PAGES  32
#define SSB_BACKUP_FLASH_REGION_START  (SSB_FLASH_REGION_START + SSB_FLASH_REGION_LENGTH + KV_PAGES * FLASH_PAGE_SIZE)
#define SSB_BACKUP_FLASH_REGION_LENGTH (SSB_BACKUP_FLASH_REGION_PAGES * FLASH_PAGE_SIZE)

/* SEC_BOOT Region for Signature Certificate */
#define SEC_BOOT_FLASH_REGION_PAGES  15
#define SEC_BOOT_FLASH_REGION_START  (SSB_BACKUP_FLASH_REGION_START + SSB_BACKUP_FLASH_REGION_LENGTH)
#define SEC_BOOT_FLASH_REGION_LENGTH (SEC_BOOT_FLASH_REGION_PAGES * FLASH_PAGE_SIZE)

#define PARTITION_TABLE_REGSION_PAGE  1
#define PARTITION_TABLE_REGION_START  (SEC_BOOT_FLASH_REGION_START + SEC_BOOT_FLASH_REGION_LENGTH)
#define PARTITION_TABLE_REGION_LENGTH  (PARTITION_TABLE_REGSION_PAGE * FLASH_PAGE_SIZE)

/* DTB Region */
#define DTB_FLASH_REGION_PAGES  (DTB_IMAGE_PAGES)
#define DTB_FLASH_REGION_START  (PARTITION_TABLE_REGION_START + PARTITION_TABLE_REGION_LENGTH)
#define DTB_FLASH_REGION_LENGTH (DTB_FLASH_REGION_PAGES * FLASH_PAGE_SIZE)

/* RECOVERY Region */
#define RECOVERY_FLASH_REGION_PAGES  (RECOVERY_IMAGE_PAGES)
#define RECOVERY_FLASH_REGION_START  (DTB_FLASH_REGION_START + DTB_FLASH_REGION_LENGTH)
#define RECOVERY_FLASH_REGION_LENGTH (RECOVERY_FLASH_REGION_PAGES * FLASH_PAGE_SIZE)

#define RECOVERY_VECTORS_LOAD_ORIGIN (RECOVERY_FLASH_REGION_START)
#define RECOVERY_VERSION_LOAD_ORIGIN (RECOVERY_VECTORS_LOAD_ORIGIN + APP_VECTORS_LENGTH)
#define RECOVERY_CHANGEID_LOAD_ORIGIN (RECOVERY_VERSION_LOAD_ORIGIN + VERSION_LENGTH)

#define RECOVERY_PROGRAM_ORIGIN (RECOVERY_CHANGEID_LOAD_ORIGIN + CHANGE_ID_LENGTH)
#define RECOVERY_PROGRAM_LENGTH ((RECOVERY_FLASH_REGION_LENGTH) - \
                                 (APP_VECTORS_LENGTH + VERSION_LENGTH + CHANGE_ID_LENGTH))

/* RESERVE Region */
#define RESERVE_FLASH_REGION_PAGES  (RESERVE_IMAGE_PAGES)
#define RESERVE_FLASH_REGION_START  (RECOVERY_FLASH_REGION_START + RECOVERY_FLASH_REGION_LENGTH)
#define RESERVE_FLASH_REGION_LENGTH (RESERVE_FLASH_REGION_PAGES * FLASH_PAGE_SIZE)

/* BT Region */
#define BT_FLASH_REGION_PAGES  (BT_IMAGE_PAGES)
#define BT_FLASH_REGION_START  (RESERVE_FLASH_REGION_START + RESERVE_FLASH_REGION_LENGTH)
#define BT_FLASH_REGION_LENGTH (BT_FLASH_REGION_PAGES * FLASH_PAGE_SIZE)

#define BT_BUILD_INFO_ORIGIN (BT_FLASH_REGION_START)
#define BT_VECTORS_LOAD_ORIGIN (BT_BUILD_INFO_ORIGIN + BUILD_INFO_LENGRH)
#define BT_VERSION_LOAD_ORIGIN (BT_VECTORS_LOAD_ORIGIN + BT_VECTORS_LENGTH)
#define BT_CHANGEID_LOAD_ORIGIN (BT_VERSION_LOAD_ORIGIN + VERSION_LENGTH)
#define DSP_CHANGEID_LOAD_ORIGIN (BT_CHANGEID_LOAD_ORIGIN + CHANGE_ID_LENGTH)

/* Fill 4 byte to align flash 8 byte */
#define BT_PROGRAM_ORIGIN (DSP_CHANGEID_LOAD_ORIGIN + CHANGE_ID_LENGTH)
#define BT_PROGRAM_LENGTH ((BT_FLASH_REGION_LENGTH) - (BT_VECTORS_LENGTH + \
                           VERSION_LENGTH + CHANGE_ID_LENGTH + CHANGE_ID_LENGTH))

/* DSP Region */
#define DSP_FLASH_REGION_PAGES  (HIFI0_IMAGE_PAGES)
#define DSP_FLASH_REGION_START  (BT_FLASH_REGION_START + BT_FLASH_REGION_LENGTH)
#define DSP_FLASH_REGION_LENGTH (DSP_FLASH_REGION_PAGES * FLASH_PAGE_SIZE)

/* DSP1 Region */
#define DSP_CODEC_FLASH_REGION_PAGES  (HIFI0_CODEC_PAGES)
#define DSP_CODEC_FLASH_REGION_START  (DSP_FLASH_REGION_START + DSP_FLASH_REGION_LENGTH)
#define DSP_CODEC_FLASH_REGION_LENGTH (DSP_CODEC_FLASH_REGION_PAGES * FLASH_PAGE_SIZE)

/* APP Region */
#define APP_FLASH_REGION_PAGES  (APP_IMAGE_PAGES)
#define APP_FLASH_REGION_START  (DSP_CODEC_FLASH_REGION_START + DSP_CODEC_FLASH_REGION_LENGTH)
#define APP_FLASH_REGION_LENGTH (APP_FLASH_REGION_PAGES * FLASH_PAGE_SIZE)

/* NV data Region */
#define NV_FLASH_REGION_PAGES  (NV_IMAGE_PAGES)
#define NV_FLASH_REGION_START  (APP_FLASH_REGION_START + APP_FLASH_REGION_LENGTH)
#define NV_FLASH_REGION_LENGTH (NV_FLASH_REGION_PAGES * FLASH_PAGE_SIZE)

/* Fota data Region */
#define FOTA_FLASH_REGION_PAGES  (FOTA_IMAGE_PAGES)
#define FOTA_FLASH_REGION_START  (NV_FLASH_REGION_START + NV_FLASH_REGION_LENGTH)
#define FOTA_FLASH_REGION_LENGTH (FOTA_FLASH_REGION_PAGES * FLASH_PAGE_SIZE)

#define APP_VECTORS_LOAD_ORIGIN (APP_FLASH_REGION_START)
#define APP_VERSION_LOAD_ORIGIN (APP_VECTORS_LOAD_ORIGIN + APP_VECTORS_LENGTH)

#define APP_PROGRAM_ORIGIN (APP_VERSION_LOAD_ORIGIN + VERSION_LENGTH)
#define APP_PROGRAM_LENGTH ((APP_FLASH_REGION_LENGTH) - (APP_VECTORS_LENGTH + VERSION_LENGTH))

/* cores image flash region start */
#define FLASH_CORE_IMAGES_START (FLASH_START + SSB_FLASH_REGION_LENGTH + SSB_BACKUP_FLASH_REGION_LENGTH + \
                                 SEC_BOOT_FLASH_REGION_LENGTH + \
                                 KV_PAGES * FLASH_PAGE_SIZE + PARTITION_TABLE_REGION_LENGTH)
/* ----------------------------------------------------------------------------------------------------------------- */
/* KV Region Defines */
/* Minimum System Configuration pages in FLASH reserved */
#define SYSTEM_RESERVED_FLASH_PAGES 0
/* Minimum reserved Non Volatile storage + Config Data. */
#define FLASH_RESERVED_LENGTH (SYSTEM_RESERVED_FLASH_PAGES * FLASH_PAGE_SIZE)

/*
 * ********************* SEC BOOT REGION *********************
 */
#define MCU_ROOT_PUBKEY_START           SEC_BOOT_FLASH_REGION_START
#define MCU_SUB_PUBKEY_START            (MCU_ROOT_PUBKEY_START + FLASH_PAGE_SIZE)
#define MCU_SSB_IMAGE_SIGN_START        (MCU_SUB_PUBKEY_START + FLASH_PAGE_SIZE)
#define MCU_SUB_PUBKEY_BACKUP_START     (MCU_SSB_IMAGE_SIGN_START + FLASH_PAGE_SIZE)
#define MCU_SSB_IMAGE_SIGN_BACKUP_START (MCU_SUB_PUBKEY_BACKUP_START + FLASH_PAGE_SIZE)

#define MCU_SEC_BOOT_SIGN_BACKUP_START  MCU_SUB_PUBKEY_BACKUP_START
#define MCU_SEC_BOOT_SIGN_BACKUP_LEN    (2 * FLASH_PAGE_SIZE)

#define MCU_CFCT_START                  (MCU_SEC_BOOT_SIGN_BACKUP_START + MCU_SEC_BOOT_SIGN_BACKUP_LEN)
#define MCU_CFCT_LEN                    FLASH_PAGE_SIZE

#define MCU_RECOVERY_IMAGE_SIGN_START   (MCU_CFCT_START + MCU_CFCT_LEN)
#define MCU_BT_IMAGE_SIGN_START         (MCU_RECOVERY_IMAGE_SIGN_START + FLASH_PAGE_SIZE)
#define MCU_DSP_IMAGE_SIGN_START        (MCU_BT_IMAGE_SIGN_START + FLASH_PAGE_SIZE)
#define MCU_DSP1_IMAGE_SIGN_START       (MCU_DSP_IMAGE_SIGN_START + FLASH_PAGE_SIZE)
#define MCU_APP_IMAGE_SIGN_START        (MCU_DSP1_IMAGE_SIGN_START + FLASH_PAGE_SIZE)
#define MCU_PARTITION_TABLE_SIGN_START  (MCU_APP_IMAGE_SIGN_START + FLASH_PAGE_SIZE)

#endif