/*
 * Copyright (c) @CompanyNameMagicTag 2015-2022. All rights reserved.
 * Description: BTH module macro conf
 */
#ifndef BTH_CONF_H
#define BTH_CONF_H
#include "stdio.h"
#include "stdlib.h"
#include "string.h"
#include "stdint.h"

#include "ivt_config.h"
#include "product.h"
#include "product_bth.h"

#define BTHCONF_INCLUDED

#if CHIP_BS25
#define BTH_FLASH var_segment("bth_flash_data")
#define BTH_LE_ONLY YES
#define BTH_BREDR_ONLY NO

#define BTH_BREDR_LE_DOUBLE NO
#define BTH_BLE_ONLY_TEST_FPGA YES // 1162 FPGA Temp by HL
#define CONFIG_LE_SINGLE_MODE 1 // 1162 FPGA Temp by HL
#define CONFIG_GLE
#elif CHIP_BRANDY
#define BTH_FLASH
#define BTH_LE_ONLY NO
#define BTH_BREDR_ONLY NO
#define BTH_BLE_ONLY_TEST_FPGA NO
#define BTH_BREDR_LE_DOUBLE YES
#define CFG_ADAPTER_BT_SUPPORT
#define BTH_AUDIO_OVER_DSP
#define SERVICE_NOT_USED_YET
#endif

#if (BTH_LE_ONLY == YES) || (BTH_BREDR_LE_DOUBLE == YES)
#include "ble_conf.h"
#endif

#if (BTH_BREDR_LE_DOUBLE == YES)
#include "br_conf.h"
#endif

/*
 * General System
 */
#define CONFIG_GNUMAKE 1
#define CONFIG_CHANGE_VERSION 1
#define CONFIG_MAJOR_VERSION 0x8
#define CONFIG_MINOR_VERSION 0x5
#define CONFIG_PATCH_LEVEL 0x0
#define CONFIG_BUILD_RELEASE 0x20121018
#define CONFIG_SECURE_COPY_FUNCTION_SUPPORTED
#undef  CONFIG_GNU
#define CONFIG_SECURE_COPY_FUNCTION_SUPPORTED

#if defined(DEBUG_ON_PC) /* run host on win PC */
#define CONFIG_MICROSOFT 1
#define CONFIG_OS_WIN32 1
#elif defined(BTH_TEST)
#undef  CONFIG_MICROSOFT
#undef  CONFIG_OS_WIN32
#else /* run host on board */
#undef  CONFIG_MICROSOFT
#undef  CONFIG_OS_WIN32
#define  CONFIG_OS_LITEOS
#endif

#undef  CONFIG_BORLAND
#undef  CONFIG_ARM
#undef  CONFIG_ARMTCC
#undef  CONFIG_DIABDCC
#undef  CONFIG_HITACHI
#undef  CONFIG_OS_LINUX
#undef  CONFIG_OS_UC
#undef  CONFIG_APP_CREATE_THREADS
#define CONFIG_SYNC_API_SUPPORTED 1
#define CONFIG_LITTLE_ENDIAN 1
#undef  CONFIG_BIG_ENDIAN
#undef  CONFIG_ALIGN_ONEBYTE
#undef  CONFIG_ALIGN_TWOBYTES
#define CONFIG_ALIGN_FOURBYTES 1
#undef  CONFIG_SUB_STRUCTURE_ALIGNED_FIXED
#undef  CONFIG_TYPE_NO_LIMIT
#define CONFIG_TYPE_BIT32_ONLY 1
#undef  CONFIG_TYPE_BIT16_ONLY
#undef  CONFIG_MEM_USER_FUNC
#define CONFIG_BLOCK_POWER (3)
#define CONFIG_BLOCK_NUMBER (3000)
#define CONFIG_CPU_BIT32 1
#undef  CONFIG_CPU_BIT16
#define CONFIG_QBUF_COUNT (20)
#undef  CONFIG_VARIABLE_VALIST
#define CONFIG_GAP 1

/*
 * HCI
 */
#if (BTH_WITH_SMART_WEAR == YES)
#define CONFIG_HCI_QOS_REALTIME_FLUSH_MAX 20
#else
#define CONFIG_HCI_QOS_REALTIME_FLUSH_MAX 99
#endif
#define CONFIG_HCI_QOS_HIGHER_INSERT_MUTILPLEX 6
#define CONFIG_HCI_TIME_CMDRTX 2000
#define CONFIG_HCI_TIME_CMDERTX 10000
#define CONFIG_HCI_TIME_PINCODE 60000
#define CONFIG_HCI_TIME_DELTA 500
#define CONFIG_HCI_TIME_ACLLAZY 5000
#define CONFIG_HCI_TIME_ACCEPT_CONNECTION 30000
#define CONFIG_HCI_TIME_LE_CREATE_CONNECTION 10000
#define CONFIG_HCI_TIME_NOCP 100
#define CONFIG_HCI_QOS_STOP_OCTETS 10240
#define CONFIG_HCI_NEW_STREAM_STRUCT_CONVERSION

#define CONFIG_HCI_REMOTE_INFO_EIR_MAX_LEN 240
#define CONFIG_HCI_REMOTE_NAME_MAX_LEN 248
#define CONFIG_HCI_LOCAL_NAME_MAX_LEN 248
#define CONFIG_HCI_READ_EXTENDED_INQUIRY_RESPONSE 240
#define CONFIG_HCI_WRITE_EXTENDED_INQUIRY_RESPONSE 240
#define CONFIG_HCI_IAC_LAP_MAX_LEN 3

#define CONFIG_HCI_SUGGESTED_MAXTX_MIN_LEN 27
#define CONFIG_HCI_SUGGESTED_MAXTX_MAX_LEN 251
#define CONFIG_HCI_SUGGESTED_MAXTX_MAX_TIME_WITH_FEATURE_DATA_LEN_EXT_AND_CODED_PHY 17040
#define CONFIG_HCI_SUGGESTED_MAXTX_MAX_TIME_WITH_FEATURE_DATA_LEN_EXT_AND_NO_CODED_PHY 2120
#define CONFIG_HCI_SUGGESTED_MAXTX_MAX_TIME_WITH_FEATURE_NO_DATA_LEN_EXT_AND_CODED_PHY 2704
#define CONFIG_HCI_SUGGESTED_MAXTX_MAX_TIME_WITH_FEATURE_NO_DATA_LEN_EXT_AND_NO_CODED_PHY 328

#define CONFIG_HCI_TIMEOUT_EXTENDED_INQUIRY_LENGTH_UNIT_MS 0.625
#define CONFIG_HCI_LOCAL_ACLDATA_LIST_LEN 3
#define CONFIG_HCI_LOCAL_START_TIMER_TIMEOUT 1000

#define CONFIG_HCI_OPC_LE_START_ENCRYPTION_TIMEOUT 40000
#define CONFIG_HCI_OPC_LE_PERIODIC_ADVERTISING_CREATE_SYNC_TIMEOUT 60000

#define CONFIG_HCI_INQUIRY_LEN_UNIT_MS 1280

#define CONFIG_HCI_SYNCHRONOUS_CONNECTION_TRANSMIT_BANDWIDTH 8000
#define CONFIG_HCI_SYNCHRONOUS_CONNECTION_RECEIVE_BANDWIDTH 8000

#define CONFIG_HCI_LE_CREATE_CONNECTION_SUPERVISION_TIMEOUT_DELTA 44

#define CONFIG_HCI_PASSKEY_LENGTH 6

#define CONFIG_HCI_HOST_SYNCHRONOUS_DATA_PACKET_LENGTH 255
#define CONFIG_HCI_HOST_TOTAL_NUM_SYNCHRONOUS_DATA_PACKETS 20

#define CONFIG_HCI_DT_GET_SUP_CMD_BIT_ERROR_NUM 511

#define CONFIG_HCI_CENTRAL_CHANNEL_FREQUENCY_MIN 2402
#define CONFIG_HCI_CENTRAL_CHANNEL_FREQUENCY_MAX 2480

/* Time to perform coded PHY scanning when user initiated */
#define HCI_TGAP_SCAN_FAST_INTERVAL_CODED          192    /* 0x00C0, 120.000ms, U:0.625 */
#define HCI_TGAP_SCAN_FAST_WINDOW_CODED            72     /* 0x0048, 90.000ms, U:0.625 */

#define HCI_TGAP_INITIAL_CONN_INTERVAL_CODED_MIN   72     /* 0x0048, 90.000ms, U:1.250 */
#define HCI_TGAP_INITIAL_CONN_INTERVAL_CODED_MAX   120    /* 0x0078, 150.000ms, U:1.250 */

#define HCI_TGAP_SUPERVISION_TO_MIN                10      /* 0x000A, 100.000ms, U:10 ms */
#define HCI_TGAP_SUPERVISION_TO_MAX                3200    /* 0x0C80, 32.000s,   U:10 ms */
#define HCI_TGAP_SUPERVISION_TO_DELTA              44      /* add a little delta */

#define HCI_TGAP_MAX_LATENCY_MIN                   0       /* 0 */
#define HCI_TGAP_MAX_LATENCY_MAX                   499     /* 0x1F3 */

#define HCI_TGAP_MAX_CE_LENGTH             0x000A  /* The Controller is not required to use these values */
#define HCI_TGAP_MIN_CE_LENGTH             0x000A  /* The Controller is not required to use these values */

#define HCI_TGAP_SLAVE_LATENCY 0

/*
 * L2cap Configuration
 */
#define CONFIG_L2CAP_RTX_TIMEOUT 3000
#define CONFIG_L2CAP_ERTX_TIMEOUT 60000
#undef  CONFIG_L2CAP_AMP_SUPPORT
#define CONFIG_L2CAP_MAX_CHANNEL_NUM 100
#define CONFIG_L2CAP_CONFIGMOVE_TIMEOUT 15000

/*
 * GAP
 */
#define CONFIG_GAP 1
#define CONFIG_GAP_ASYNC_API_SUPPORTED 1
#ifdef CONFIG_SYNC_API_SUPPORTED
#define CONFIG_GAP_SYNC_API_SUPPORTED 1
#endif

#define CONFIG_GAP_DEVICE_DISCOVERY_INQUIRY_DURATION_MS 1280

#define CONFIG_GAP_EXTENDED_ADVERTISING_DURATION_MS 10
#define CONFIG_GAP_EXTENDED_SCAN_DURATION_MS 10
#define CONFIG_GAP_EXTENDED_SCAN_PERIOD_MS 1280
#define CONFIG_GAP_EXTENDED_SCAN_WINDOW_MS 100
#define CONFIG_GAP_LE_EXT_REQ_LIST_MAX_LEN 9
#define CONFIG_GAP_CONTEXT_MAX_LEN 249

/*
 * ATT
 */
#define CONFIG_GATT_CONNECT_TIMEOUT_MIN 10
#define CONFIG_GATT_CONNECT_TIMEOUT_MAX 60000

/*
 * Bluetooth SDK APIs
 */
#ifdef CFG_BT_CORE_STACK_DEBUG
#define CONFIG_BTSDK 1
#else
#undef CONFIG_BTSDK
#endif

/*
 * Debug
 */
#ifdef DEBUG_ON_PC
#define CFG_BT_CORE_STACK_DEBUG
#endif
#ifdef CFG_BT_CORE_STACK_DEBUG
#define CONFIG_DEBUG_SYMBOL 1
#define CONFIG_DEBUG 1
#define CONFIG_DBG_TIMER 1
#undef  CONFIG_DBG_TIMER_ALL
#define CONFIG_DBG_L2CAP_INFO 1
#define CONFIG_DBG_L2CAP_PDU 1
#define CONFIG_DBG_L2CAP_ERT 1
#define CONFIG_DBG_RFCOMM 1
#define CONFIG_DBG_SDP 1
#define CONFIG_DBG_AVCTP 1
#define CONFIG_DBG_AVRCP 1
#define CONFIG_DBG_AVDTP 1
#define CONFIG_DBG_HFP 1
#define CONFIG_DBG_OBEX 1
#else
#undef CONFIG_DEBUG_SYMBOL
#undef CONFIG_DEBUG
#undef CONFIG_CHECK_STACK
#undef CONFIG_MEMORY_LEAK_DETECT
#undef CONFIG_DBG_TIMER
#undef CONFIG_DBG_TIMER_ALL
#undef CONFIG_DBG_HCI
#undef CONFIG_DBG_HCIRAW
#undef CONFIG_DBG_L2CAP
#undef CONFIG_DBG_L2CAP_INFO
#undef CONFIG_DBG_L2CAP_PDU
#undef CONFIG_DBG_L2CAP_ERT
#undef CONFIG_DBG_RFCOMM
#undef CONFIG_DBG_SDP
#undef CONFIG_DBG_AVCTP
#undef CONFIG_DBG_AVRCP
#undef CONFIG_DBG_AVDTP
#undef CONFIG_DBG_HFP
#undef CONFIG_DBG_OBEX
#undef CONFIG_DBG_SMP
#undef CONFIG_DBG_ATT
#endif /* CFG_BT_CORE_STACK_DEBUG */

#if defined(CONFIG_TWS) && !defined(CONFIG_MEMORY_LEAK_DETECT) && !defined(VERSION_FACTORY)
#define CONFIG_HW_MEMORY_DEBUG
#endif
#ifdef CONFIG_HW_MEMORY_DEBUG
#define CONFIG_HW_MEMORY_LEAK_DEBUG_ON_BUFFER
#endif

#define CONFIG_HEAP_SECURE_THRESHOLD 1408
#define CONFIG_SYNC_API_SUPPORTED 1

#define CONFIG_PAGE_SCAN_INTERVAL 0x800 /* slots, 1.28s */
#define CONFIG_PAGE_SCAN_WINDOW   0x12  /* slots, 11.25ms */
#define CONFIG_PAGE_SCAN_TYPE 0x01 /* GI scan */

#ifndef CONFIG_TWS
#undef CONFIG_HITWS
#define CONFIG_BT_STACK_DONE
#endif

#ifdef CONFIG_TWS
#define CONFIG_REL_VOL
#define CONFIG_BT_CLEANUP
#endif

#ifdef BOX_COMMUNICATION_ENABLE
#undef CONFIG_BT_CLEANUP
#endif

/* 裁剪过程中单独关闭，后期考虑与STACK宏统一 by HL */
#ifdef CFG_ADAPTER_BT_SUPPORT
#define CONFIG_ADAPTER_SPP
#define CONFIG_ADAPTER_A2DP
#define CONFIG_ADAPTER_HFP
#define CONFIG_ADAPTER_AVRCP
#define CONFIG_ADAPTER_HFP_HF
#define CONFIG_ADAPTER_HFP_AG
#endif /* 裁剪过程中单独关闭，后期考虑与STACK宏统一 by HL */
#endif
