/*
 * Copyright (c) @CompanyNameMagicTag 2022-2022. All rights reserved.
 * Description:  Interrupt DRIVER
 * Author: @CompanyNameTag
 * Create:  2022-10-15
 */
#include "stdint.h"
#include "chip_core_irq.h"

uint8_t g_aucIntPri[BUTT_IRQN] = {
    0,                       // RESERVED0_IRQN                     =  0,
    0,                       // RESERVED1_IRQN                     =  1,
    0,                       // RESERVED2_IRQN                     =  2,
    1,                       // Machine software interrupt         =  3,
    0,                       // RESERVED3_IRQN                     =  4,
    0,                       // RESERVED4_IRQN                     =  5,
    0,                       // RESERVED5_IRQN                     =  6,
    1,                       // Machine timer interrupt            =  7,
    0,                       // RESERVED6_IRQN                     =  8,
    0,                       // RESERVED7_IRQN                     =  9,
    0,                       // RESERVED8_IRQN                     = 10,
    1,                       // Machine external interrupt         = 11,
    0,                       // RESERVED9_IRQN                     = 12,
    0,                       // RESERVED10_IRQN                    = 13,
    0,                       // RESERVED11_IRQN                    = 14,
    0,                       // RESERVED12_IRQN                    = 15,
    1,                       // BT_INT0_IRQN                       = 16,
    1,                       // BT_INT1_IRQN                       = 17,
    1,                       // DSP0_INT0_IRQn                     = 18,
    1,                       // DSP0_INT1_IRQn                     = 19,
    0,                       // DSP1_INT0_IRQn                     = 20,
    0,                       // DSP1_INT1_IRQn                     = 21,
    0,                       // MCPU_PCLR_OK_IRQn                  = 22,
    0,                       // ULP_GPIO_IRQN                      = 23,
    3,                       // GPIO_0_IRQN                        = 24,
    3,                       // GPIO_1_IRQN                        = 25,
    1,                       // GPIO_2_IRQn                        = 26,
    1,                       // GPIO_3_IRQn                        = 27,
    1,                       // GPIO_4_IRQn                        = 28,
    1,                       // RESERVED_13_IRQn                   = 29,
    1,                       // RESERVED_14_IRQn                   = 30,
    1,                       // UART_1_IRQN                        = 31,
    1,                       // UART_0_IRQN                        = 32,
    1,                       // MEM2MCU_QSPI0_2CS_IRQN             = 33,
    1,                       // QSPI1_CS_IRQn                      = 34,
    1,                       // QSPI2_CS_IRQn                      = 35,
    1,                       // OPI_INT_IRQn                       = 36,
    1,                       // M_WAKEUP_IRQN                      = 37,
    1,                       // M_SLEEP_IRQN                       = 38,
    1,                       // RESERVED_15_IRQn                   = 39,
    1,                       // RESERVED_16_IRQn                   = 40,
    1,                       // RESERVED_17_IRQn                   = 41,
    1,                       // RTC_0_IRQN                         = 42,
    1,                       // TIMER_0_IRQN                       = 43,
    1,                       // TIMER_1_IRQN                       = 44,
    1,                       // TIMER_2_IRQN                       = 45,
    1,                       // TIMER_3_IRQN                       = 46,
    6,                       // M_SDMA_IRQN                        = 47,
    6,                       // M_DMA_IRQN                         = 48,
    5,                       // SPI_M_IRQN                         = 49,
    6,                       // SPI_M_S_0_IRQN                     = 50,
    5,                       // SPI_M_S_1_IRQN                     = 51,
    1,                       // I2C_0_IRQN                         = 52,
    3,                       // I2C_1_IRQN                         = 53,
    3,                       // I2C_2_IRQN                         = 54,
    3,                       // I2C_3_IRQN                         = 55,
    1,                       // MAD_IRQn                           = 56,
    1,                       // VAD_MERGE_IRQn                     = 57,
    1,                       // NUM_INTERRUPT_GMMU                 = 58,
    4,                       // RESERVED_43_IRQN                   = 59,
    4,                       // SEC_INT_IRQN                       = 60,
    1,                       // PWM_0_IRQN                         = 61,
    1,                       // PWM_1_IRQN                         = 62,
    1,                       // PWM_2_IRQN                         = 63,
    1,                       // PWM_3_IRQN                         = 64,
    1,                       // PWM_4_IRQN                         = 65,
    1,                       // PWM_5_IRQN                         = 66,
    1,                       // RESERVED_51_IRQn                   = 67,
    1,                       // PMU_CMU_ERR_IRQN                   = 68,
    1,                       // RESERVED_53_IRQn                   = 69,
    6,                       // ADC_IRQn                           = 70,
    4,                       // MEM_SUB_MONITOR_IRQn               = 71,
    1,                       // B_SUB_MONITOR_IRQn                 = 72,
    1,                       // COMRAM_MONITOR_IRQN                = 73,
    1,                       // RESERVED_58_IRQn                   = 74,
    1,                       // RESERVED_59_IRQn                   = 75,
    1,                       // SDIO2MCU_SDIO_H_IRQn               = 76,
    1,                       // SDIO2MCU_SDIO_H_WAKEUP_IRQn        = 77,
    1,                       // EMMC_IRQn                          = 78,
    1,                       // SDIO2MCU_EMMC_WAKEUP_IRQn          = 79,
    1,                       // RESERVED_64_IRQn                   = 80,
    1,                       // EH2H_INT_IRQn                      = 81,
    1,                       // NUM_INTERRUPT_DPU                  = 82,
    1,                       // NUM_INTERRUPT_VAU                  = 83,
    1,                       // NUM_INTERRUPT_MIPI                 = 84,
    1,                       // NUM_INTERRUPT_SENSOR_HUB_DPU1_TE   = 85,
    1,                       // NUM_INTERRUPT_JPEG                 = 86,
    1,                       // RESERVED_71_IRQn                   = 87,
    1,                       // DSP0_ADDR_MON_IRQn                 = 88,
    1,                       // RESERVED_73_IRQn                   = 89,
    1,                       // DSP_WDT_IRQn                       = 90,
    1,                       // D2MCU_DSP0_WDOG1_INT_IRQn          = 91,
    1,                       // RESERVED_76_IRQn                   = 92,
    1,                       // RESERVED_77_IRQn                   = 93,
    1,                       // RESERVED_78_IRQn                   = 94,
    1,                       // RESERVED_79_IRQn                   = 95,
    1,                       // RESERVED_80_IRQn                   = 96,
};
