/*
 * Copyright (c) @CompanyNameMagicTag 2021-2022. All rights reserved.
 * Description: data config
 */
#ifndef DATA_CONFIG_H
#define DATA_CONFIG_H

#include "custdefs.h"
#include "bts_def.h"
#include "mpc_struct.h"
#include "stack_gap_if.h"
#ifdef __cplusplus
#if __cplusplus
extern "C" {
#endif
#endif
typedef enum {
    BT_CONFIG_STATUS_SUCESS,
    BT_CONFIG_STATUS_FAIL,
    BT_CONFIG_STATUS_TIMEOUT,
    BT_CONFIG_STATUS_WAIT_FINISH,
} bt_config_status;

typedef enum {
    BT_CONFIG_ID_START,
    BT_CONFIG_ID_CALIBRATION,
    BT_CONFIG_ID_PRODUCT_TYPE,
    BT_CONFIG_ID_BLE_SYS_MASK,
    BT_CONFIG_ID_BLE_SMP_KEY,
    BT_CONFIG_ID_END
} bt_data_config_id;
typedef enum {
    BT_CONFIG_SYS_MASK_KEY_FROM_BTC,
} bt_config_system_mask;
typedef struct {
    bt_data_config_id        config_id;
    uint16_t                 config_offset;
    uint16_t                 config_length;
} bt_config_data_t;

typedef struct smp_key { /* Master role security database */
    /* as Security Level, both side share this length, by pairing_request and response min */
    uint8_t ltk_len;
    uint8_t fea;                        /* etc, SMP_KEYFEA_ECDH */

    /* Local sent to remote information */
    uint8_t div[2];                    /* 16bits, 2octets, Peripherial(slave) distributed DIV for remote(Master) */

    /* Remote sent to local, or LESC derived on both sides */
    uint8_t ltk[16];                    /* corresponding to Public/Static address or IRK(RPA) */
    uint8_t ediv[2];                    /* eDIV and Rand are only used in legacy LTK encryption(no LESC) */
    uint8_t rand[8];                    /* Encryption keys */
    uint8_t irk[16];                    /* Resolveable address */
    /* Signature, CSRK_DECODE. CSRK_ENCODE is generated by d1(ER, DIV, 1) locally */
    uint8_t csrk[16];
} smp_key_stru_t;

typedef struct {            /* Keys that indexes by addr */
    struct hci_address_stru addr;    /* peer address, not sure dule-mode */
    smp_key_stru_t key;            /* Bonding information */
} smp_key_store_stru_t;

/****************define config data length start*************************************/
#define BT_CONFIG_DATA_CALIBRATION_LEN CALIBRATION_PARAMS_LENGTH
#define PRODUCT_TYPE_LEN (sizeof(uint8_t))
#define BLE_SYS_MASK_LEN (sizeof(uint32_t))
#define BLE_SMP_DATA_LEN (sizeof(smp_key_store_stru_t) * BTH_BLE_PAIRING_MAX)
/****************define config data offset start*************************************/
#define BT_CONFIG_DATA_ADDRESS_BASE      0x0000
#define BT_CONFIG_DATA_CALIBRATION_OFFSET BT_CONFIG_DATA_ADDRESS_BASE
#define PRODUCT_TYPE_OFFSET (BT_CONFIG_DATA_CALIBRATION_OFFSET + BT_CONFIG_DATA_CALIBRATION_LEN)
#define BLE_SYS_MASK_OFFSET (PRODUCT_TYPE_OFFSET + PRODUCT_TYPE_LEN)
#define BLE_SMP_DATA_ADDRESS_OFFSET (BLE_SYS_MASK_OFFSET + BLE_SYS_MASK_LEN)
#define BT_CONFIG_DATA_ADDRESS_END (BLE_SMP_DATA_ADDRESS_OFFSET + BLE_SMP_DATA_LEN)
#define BT_CONFIG_DATA_MEM_LEN  (BT_CONFIG_DATA_ADDRESS_END - BT_CONFIG_DATA_ADDRESS_BASE)
#define BD_CONFIG_SYNC_DATA_SIZE BT_CONFIG_DATA_MEM_LEN
typedef struct {
    uint8_t bd_addr[BD_ADDR_LEN];
    uint8_t phone_bd_addr[BD_ADDR_LEN];
    uint8_t bd_name[BD_NAME_MAX_LEN];
    uint8_t config_data[BD_CONFIG_SYNC_DATA_SIZE];
} product_data_config;
#define bt_config_set_mask_bit(data, bit, flg) (((data) & (uint32_t)(~(1 << (bit)))) | ((flg) << (bit)))
product_data_config* bt_acore_get_data_config(void);
void bt_acore_get_bt_addr(uint8_t *bdaddr, uint32_t size);
void bt_acore_get_phone_bt_addr(uint8_t *bdaddr);
void bt_acore_get_bt_name(uint8_t *bdname, uint32_t size);
void bt_acore_get_config_sync_global(uint16_t offset, uint8_t *data, uint32_t len);
void bt_acore_set_config_sync_global(uint16_t offset, const uint8_t *data, uint32_t len);
uint8_t bt_sync_config_from_file_to_global(void);
uint8_t bt_sync_config_from_global_to_file(void);
void bt_acore_get_config_sync_flash(uint8_t *data, uint32_t len);
void bt_acore_set_config_sync_flash(const uint8_t *data, uint32_t len);
int32_t bt_acore_config_data_write(bt_data_config_id data_id, const void* data_write, uint16_t data_length);
uint32_t bt_acore_config_data_read(bt_data_config_id data_id, void* data_read, uint16_t data_length);
void bt_acore_config_bypass_mode(void);
void bt_acore_save_smp_key(smp_key_store_stru_t *key_data);
void bt_acore_get_smp_keys(smp_key_store_stru_t *recover_key, uint8_t *key_num);
void bt_acore_get_product_type(uint8_t *product_type);
void bt_acore_get_system_config(uint32_t *system_config);
void bt_acore_get_calibration_data(uint8_t *calibration_data, uint16_t data_length);
void bt_acore_delete_smp_key(struct hci_address_stru *delete_addr, uint8_t *delete_num);
void bt_acore_delete_single_smp_key(struct hci_address_stru *delete_addr);
errcode_t bt_acore_get_bonded_device(bd_addr_t *bonded_device, uint16_t *number);
void bt_acore_set_sys_config(uint8_t is_key_from_btc);
void bt_acore_set_product_type(uint8_t product_type);
uint8_t bt_acore_get_local_dev_info(uint16_t kvalue_max_length, uint16_t *kvalue_length, uint8_t *kvalue);
uint32_t bt_acore_set_local_dev_info(const uint8_t *kvalue, uint16_t kvalue_length);
uint32_t bt_acore_get_paired_dev_info(uint16_t kvalue_max_length, uint16_t *kvalue_length, uint8_t *kvalue);
uint32_t bt_acore_set_paired_dev_info(const uint8_t *kvalue, uint16_t kvalue_length);
#ifdef __cplusplus
#if __cplusplus
}
#endif /* __cpluscplus */
#endif /* __cpluscplus */
#endif /* DATA_CONFIG_H */
