#ifndef INTERRUPT_CONFIG_H
#define INTERRUPT_CONFIG_H

#include "FreeRTOSConfig.h"

#ifdef __cplusplus
#if __cplusplus
extern "C" {
#endif /* __cplusplus */
#endif /* __cplusplus */

#define OS_RISCV_SYS_VECTOR_CNT         configHWI_SYS_VECTOR_CNT
#define OS_RISCV_MIE_IRQ_VECTOR_CNT     6
#define OS_RISCV_LOCAL_IRQ_VECTOR_CNT   (OS_RISCV_MIE_IRQ_VECTOR_CNT + OS_RISCV_SYS_VECTOR_CNT)
#define OS_RISCV_MIE_IRQ_VECTOR_ALL_CNT  OS_RISCV_LOCAL_IRQ_VECTOR_CNT

#define NUM_HAL_INTERRUPT_SWI           3
#define NUM_HAL_INTERRUPT_NMI           12
#define NUM_HAL_INTERRUPT_TIMER0      (0 + OS_RISCV_SYS_VECTOR_CNT)
#define NUM_HAL_INTERRUPT_TIMER1      (1 + OS_RISCV_SYS_VECTOR_CNT)
#define NUM_HAL_INTERRUPT_TIMER2      (2 + OS_RISCV_SYS_VECTOR_CNT)
#define NUM_HAL_INTERRUPT_TIMER3      (3 + OS_RISCV_SYS_VECTOR_CNT)
#define NUM_HAL_INTERRUPT_TIMER4      (4 + OS_RISCV_SYS_VECTOR_CNT)
#define NUM_HAL_INTERRUPT_TIMER5      (5 + OS_RISCV_SYS_VECTOR_CNT)
#define NUM_HAL_INTERRUPT_TIMER6      (6 + OS_RISCV_SYS_VECTOR_CNT)
#define NUM_HAL_INTERRUPT_TIMER7      (7 + OS_RISCV_SYS_VECTOR_CNT)
#define NUM_HAL_INTERRUPT_DMA         (8 + OS_RISCV_SYS_VECTOR_CNT)
#define NUM_HAL_INTERRUPT_UART0       (9 + OS_RISCV_SYS_VECTOR_CNT)  /* ACPU uart */
#define NUM_HAL_INTERRUPT_UART3       (24 + OS_RISCV_SYS_VECTOR_CNT) /* share uart */

#define NUM_HAL_INTERRUPT_SSP         (12 + OS_RISCV_SYS_VECTOR_CNT)
#define NUM_HAL_INTERRUPT_LSADC       (14 + OS_RISCV_SYS_VECTOR_CNT)
#define NUM_HAL_INTERRUPT_EMMC        (15 + OS_RISCV_SYS_VECTOR_CNT)
#define NUM_HAL_INTERRUPT_FMC         (16 + OS_RISCV_SYS_VECTOR_CNT)
#define NUM_HAL_INTERRUPT_USB         (17 + OS_RISCV_SYS_VECTOR_CNT)
#define NUM_HAL_INTERRUPT_SDIO        (18 + OS_RISCV_SYS_VECTOR_CNT)
#define NUM_HAL_INTERRUPT_TDE         (19 + OS_RISCV_SYS_VECTOR_CNT)
#define NUM_HAL_INTERRUPT_VDP         (20 + OS_RISCV_SYS_VECTOR_CNT)
#define NUM_HAL_INTERRUPT_MIPI        (21 + OS_RISCV_SYS_VECTOR_CNT)
#define NUM_HAL_INTERRUPT_RAM_APC_ERR (22 + OS_RISCV_SYS_VECTOR_CNT)
#define NUM_HAL_INTERRUPT_IPC_TO_APP  (31 + OS_RISCV_SYS_VECTOR_CNT)

#define NUM_HAL_INTERRUPT_SEC_DBC_TO_ACPU0 (64 + OS_RISCV_SYS_VECTOR_CNT)
#define NUM_HAL_INTERRUPT_SEC_DBC_TO_ACPU1 (65 + OS_RISCV_SYS_VECTOR_CNT)
#define NUM_HAL_INTERRUPT_SEC_DBC_TO_ACPU2 (66 + OS_RISCV_SYS_VECTOR_CNT)
#define NUM_HAL_INTERRUPT_SEC_DBC_TO_ACPU3 (67 + OS_RISCV_SYS_VECTOR_CNT)
#define NUM_HAL_INTERRUPT_SEC_DBC_TO_ACPU4 (68 + OS_RISCV_SYS_VECTOR_CNT)
#define NUM_HAL_INTERRUPT_SFC         (69 + OS_RISCV_SYS_VECTOR_CNT)
#define NUM_HAL_INTERRUPT_AUDIO       (70 + OS_RISCV_SYS_VECTOR_CNT)
#define NUM_HAL_INTERRUPT_LP_UART_TX  (71 + OS_RISCV_SYS_VECTOR_CNT)
#define NUM_HAL_INTERRUPT_LP_UART_RX  (72 + OS_RISCV_SYS_VECTOR_CNT)
#define NUM_HAL_INTERRUPT_GPIO0       (73 + OS_RISCV_SYS_VECTOR_CNT)
#define NUM_HAL_INTERRUPT_GPIO1       (74 + OS_RISCV_SYS_VECTOR_CNT)
#define NUM_HAL_INTERRUPT_GPIO2       (75 + OS_RISCV_SYS_VECTOR_CNT)
#define NUM_HAL_INTERRUPT_GPIO3       (76 + OS_RISCV_SYS_VECTOR_CNT)

#define NUM_HAL_INTERRUPT_RTC0        (89 + OS_RISCV_SYS_VECTOR_CNT)
#define NUM_HAL_INTERRUPT_RTC1        (90 + OS_RISCV_SYS_VECTOR_CNT)
#define NUM_HAL_INTERRUPT_RTC2        (91 + OS_RISCV_SYS_VECTOR_CNT)
#define NUM_HAL_INTERRUPT_RTC3        (92 + OS_RISCV_SYS_VECTOR_CNT)
#define NUM_HAL_INTERRUPT_SENSOR_HUB_RTC0  (93 + OS_RISCV_SYS_VECTOR_CNT)
#define NUM_HAL_INTERRUPT_SENSOR_HUB_RTC1  (94 + OS_RISCV_SYS_VECTOR_CNT)
#define NUM_HAL_INTERRUPT_SENSOR_HUB_UART0 (95 + OS_RISCV_SYS_VECTOR_CNT)
#define NUM_HAL_INTERRUPT_SENSOR_HUB_UART1 (96 + OS_RISCV_SYS_VECTOR_CNT)
#define NUM_HAL_INTERRUPT_SENSOR_HUB_SPI0  (97 + OS_RISCV_SYS_VECTOR_CNT)
#define NUM_HAL_INTERRUPT_SENSOR_HUB_SPI1  (98 + OS_RISCV_SYS_VECTOR_CNT)
#define NUM_HAL_INTERRUPT_SENSOR_HUB_I2C0  (99 + OS_RISCV_SYS_VECTOR_CNT)
#define NUM_HAL_INTERRUPT_SENSOR_HUB_I2C1  (100 + OS_RISCV_SYS_VECTOR_CNT)
#define NUM_HAL_INTERRUPT_SENSOR_HUB_I2C2  (101 + OS_RISCV_SYS_VECTOR_CNT)
#define NUM_HAL_INTERRUPT_SENSOR_HUB_I2C3  (102 + OS_RISCV_SYS_VECTOR_CNT)
#define NUM_HAL_INTERRUPT_SENSOR_HUB_I2C4  (103 + OS_RISCV_SYS_VECTOR_CNT)
#define NUM_HAL_INTERRUPT_SENSOR_HUB_DNTC0 (104 + OS_RISCV_SYS_VECTOR_CNT)
#define NUM_HAL_INTERRUPT_SENSOR_HUB_DNTC1 (105 + OS_RISCV_SYS_VECTOR_CNT)
#define NUM_HAL_INTERRUPT_SENSOR_HUB_IPC0  (106 + OS_RISCV_SYS_VECTOR_CNT)

#define NUM_HAL_INTERRUPT_SENSOR_HUB_QSPI    (110 + OS_RISCV_SYS_VECTOR_CNT)
#define NUM_HAL_INTERRUPT_SENSOR_HUB_VDP1_TE (111 + OS_RISCV_SYS_VECTOR_CNT)
#define NUM_HAL_INTERRUPT_SENSOR_HUB_DMA     (112 + OS_RISCV_SYS_VECTOR_CNT)

#define NUM_HAL_INTERRUPT_IR_TX     (113 + OS_RISCV_SYS_VECTOR_CNT)
#define NUM_HAL_INTERRUPT_IR_RX     (114 + OS_RISCV_SYS_VECTOR_CNT)
#define NUM_HAL_INTERRUPT_SDCC      (115 + OS_RISCV_SYS_VECTOR_CNT)

#define NUM_HAL_INTERRUPT_WKUP      (116 + OS_RISCV_SYS_VECTOR_CNT)
#define NUM_HAL_INTERRUPT_SLP       (117 + OS_RISCV_SYS_VECTOR_CNT)

#define NUM_HAL_INTERRUPT_TSENSOR       (118 + OS_RISCV_SYS_VECTOR_CNT)
#define NUM_HAL_INTERRUPT_PSRAM_SEC     (119 + OS_RISCV_SYS_VECTOR_CNT)
#define NUM_HAL_INTERRUPT_PMU_CMU_ERR   (120 + OS_RISCV_SYS_VECTOR_CNT)
#define NUM_HAL_INTERRUPT_ACCESS_MEM    (121 + OS_RISCV_SYS_VECTOR_CNT)
#define NUM_HAL_INTERRUPT_SOFT0         (122 + OS_RISCV_SYS_VECTOR_CNT)
#define NUM_HAL_INTERRUPT_SOFT1         (123 + OS_RISCV_SYS_VECTOR_CNT)
#define NUM_HAL_INTERRUPT_SDCC_WAKEUP   (124 + OS_RISCV_SYS_VECTOR_CNT)
#define NUM_HAL_INTERRUPT_CAPSENSOR     (125 + OS_RISCV_SYS_VECTOR_CNT)

#define NUM_HAL_INTERRUPT_NONE          configHWI_PRIO_IGNORE

#define NUM_HAL_INTERRUPT_TIMER         NUM_HAL_INTERRUPT_TIMER0
#define NUM_HAL_INTERRUPT_HRTIMER       NUM_HAL_INTERRUPT_TIMER1
#define OS_TICK_INT_NUM                 7

#ifdef __cplusplus
#if __cplusplus
}
#endif /* __cplusplus */
#endif /* __cplusplus */

#endif /* _ASM_HAL_PLATFORM_INTS_H */
