#ifndef __LIBC_TYPES__
#define __LIBC_TYPES__


#define MICROSECONDS_PER_SECOND         (1000000LL)
#define NANOSECONDS_PER_SECOND          (1000000000LL)
#define NANOSECONDS_PER_MILLISECOND     (1000000LL)
#define MILLISECONDS_PER_SECOND         (1000LL)
#define MICROSECONDS_PER_MILLISECOND    (1000LL)
#define NANOSECONDS_PER_MICROSECONDS    (1000LL)
#define MICROSECONDS_ADJ_PER_SECOND     (500LL)
#ifdef __FREERTOS__
#define NANOSECONDS_PER_TICK           (NANOSECONDS_PER_SECOND / configTICK_RATE_HZ)
#define KERNEL_TICK_PER_SECOND         configTICK_RATE_HZ
#define SCHED_CLOCK_INTETRVAL_TICKS     configTICK_RATE_HZ
#endif

#endif
